[tool:pytest]
testpaths = tests
python_paths = .
addopts = -v --tb=short
pythonpath = .
minversion = 6.0
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
